### ISSUE TITLE
Selectively monitor containers with label

### ISSUE THREAD

**Issue by eliottvincent** [pyouroboros/ouroboros#104]
Hello,

Do you plan to support selective monitoring of containers via label?
Like the `--label-enable` feature of Watchtower: [here](https://github.com/v2tec/watchtower#selectively-watching-containers)

Thanks for this awesome project!

Eliott

**Comment by DirtyCajunRice** [comment]
is —monitor not the feature you are asking about?

**Comment by eliottvincent** [comment]
With `--monitor` you can indeed selectively monitor containers, but it's based on their **name**, not on the **presence of a Docker label**.

**Comment by DirtyCajunRice** [comment]
So that is interesting in the aspect that `com.centurylinklabs.watchtower.enable` is defined by watchtower as the label you have to apply to your images. How go you see this handling images that are not of your own creation?

**Comment by ShakataGaNai** [comment]
I'm going to plus one the support for [compose labels](https://docs.docker.com/compose/compose-file/#labels-1) as that's very handy for keeping certain portions auto-updated (like say backend/processing microservices) and avoiding updating components that are update intolerant (ex databases & ingestion services).

**Comment by DirtyCajunRice** [comment]
Fixed in develop

**Comment by eliottvincent** [comment]
Well that was fast! Thanks a lot @DirtyCajunRice
