### ISSUE TITLE
Start/Stop containers in sequence

### ISSUE THREAD

**Issue by DirtyCajunRice** [pyouroboros/ouroboros#106]
https://github.com/v2tec/watchtower#linked-containers

**Comment by DirtyCajunRice** [comment]
Im starting to second guess this one. 
https://docs.docker.com/compose/compose-file/#depends_on
only worries about it if the other service does not already exist and is not already started... and
https://docs.docker.com/compose/compose-file/compose-file-v2/#external_links
which is the successor to links no longer expresses dependency requirements. I feel building this in would effectively be "anti-docker-istic"

thoughts?

**Comment by tlkamp** [comment]
I think it's on us to be predictable. I wouldn't update anything unless specified in `--monitor`.

Obviously if they choose to leave `monitor` empty, everything is updated at that point.

**Comment by DirtyCajunRice** [comment]
Exists in develop :)
