### ISSUE TITLE
Pushover notification message displays incorrect info

### ISSUE THREAD

**Issue by UniverseXXX** [pyouroboros/ouroboros#108]
"Containers updated" line shows incorrect amount. My understanding that this is aggregated number of the updated containers.

![unadjustednonraw_thumb_25a4](https://user-images.githubusercontent.com/7465472/51206429-edfcb700-18ff-11e9-98b0-82fb5cb8e1cd.jpg)

![unadjustednonraw_thumb_25a5](https://user-images.githubusercontent.com/7465472/51206441-f5bc5b80-18ff-11e9-9ff2-a6c1d100457a.jpg)

**Comment by DirtyCajunRice** [comment]
the container updates are a per socket number.

**Comment by UniverseXXX** [comment]
This is misleading information though. 
This is ridiculous! Moving back to WatchTower as this project team has implemented all my proposals in completely unacceptable way. Notifications to HealthChecks self hosted server not working as it should be, Pushover notifications won't show correct information. In all proposals Ive submitted the  above has been working without issues. Disappointing, wasting of my time.

**Comment by DirtyCajunRice** [comment]
Its not, as it shows you the socket in question, followed by the updates on that socket. Watchtower only allows a single host so you wont be gaining any benefit from that migration, nor does it do healthchecks whatsoever. A threat to an open-source project that has no monetary perview is no threat at all.

**Comment by circa10a** [comment]
@UniverseXXX Given you did have this working before and it wasn't implemented the way you like, is it unacceptable just to fork, add what you would like in the way that works for you and run it locally? Well since it's MIT licensed, you could even publish it docker hub under your own name.

**Comment by DirtyCajunRice** [comment]
To ensure others can see the context clues you have intentionally neglected to provide:
* Webhooks were integrated to allow a json post per interval to allow a "healthcheck" post to any url with 'hc-ping' in the url. 
* Any individual that has the tenacity to build a docker container with nginx reverse proxying ANY url to a url with hc-ping in it will reap the benefits of this, as its nothing to do with it being their HOSTED service.
* I personally made an account on hc-ping and they offer 20 endpoints at no charge to every account if you so choose

> If you set out to be liked, you would be prepared to compromise on anything at any time, and you would achieve nothing. ~ Margaret Thatcher

**Comment by circa10a** [comment]
@UniverseXXX we recently implemented a new notification system. I encourage you to read the docs and give it a go
