### ISSUE TITLE
Missing docker-compose.yml from documentation

### ISSUE THREAD

**Issue by scobby** [pyouroboros/ouroboros#120]
can you please reupload that file?
thx

**Comment by DirtyCajunRice** [comment]
We will add a docker-compose example to the wiki. Sorry about that. It was our intention to do it right when we swapped over but we have made quite a few changes that make the wiki a larger project than initially anticipated.

**Comment by circa10a** [comment]
@scobby Does this help?
https://github.com/pyouroboros/ouroboros/wiki/Usage#docker-compose
