### ISSUE TITLE
Blackout hours

### ISSUE THREAD

**Issue by nemchik** [pyouroboros/ouroboros#127]
Per discussion in Discord:

I would like to see a way to limit updates to only run during a specific allowed (whitelist) hours window OR not run during a blackout window. Ex: I only want updates to run between 2am and 4am.

**Comment by tlkamp** [comment]
Thanks for the issue!

I'm on the fence about this one since it would be very close to cron scheduling, which we said we're not going to implement. 

A current work around for this would be to use cron in combination with the `--run-once` argument.

**Comment by DirtyCajunRice** [comment]
after the extended conversation on discord, the consensus is that with the current scope of the project, it is not something that would be implemented cleanly, lightly, or efficiently. I can promise that if something does change with the state of scheduling, and this becomes feasible i will absolutely re-open!

**Comment by dannysauer** [comment]
Alternate workaround: start/stop service on a schedule so it's simply not running during blackout hours.
