### ISSUE TITLE
Notification on startup

### ISSUE THREAD

**Issue by cybermcm** [pyouroboros/ouroboros#138]
Now that mail notification was implemented (Thank you very much!) it would be very helpful to have the possibility to check if the config is working.
Watchtower sends an email upon start, maybe a switchable config to send a startup email?

**Comment by DirtyCajunRice** [comment]
can you give an example output of watchtower's startup email?

**Comment by cybermcm** [comment]
a very simple mail.
```
Subject:
Watchtower updates on 4224e8b13789
Body:
2019-01-23 20:59:51 (info): First run: 2019-01-23 21:04:51 +0000 UTC
```
Just an info/confirmation that mail notification is working (it's not editable, it will be send every time watchtower starts). IMO it should be off but with an option to be enabled (Env setting).

**Comment by DirtyCajunRice** [comment]
I absolutely think this can be added. It will be a little more complex than just an email as we have multiple notification options, but i will work on it

**Comment by DirtyCajunRice** [comment]
updates in develop. Wiki update shortly.
