### ISSUE TITLE
Feature request: filter on stack

### ISSUE THREAD

**Issue by gotson** [pyouroboros/ouroboros#139]
Hi,

in my current configuration i have one `docker-compose` stack with many services that i want auto-updated (that includes ouroboros), but i also run hass.io which spins its own containers, and auto-update them.

It would be great if ouroboros could filter on stack in addition to container name, so i could watch all the container in my stack, but not the ones that have no stack.

**Comment by DirtyCajunRice** [comment]
dockerpy is completely unaware of docker-compose. docker-compose has no intention of ever making a client side module. Therefore we have no sane way of getting that information :/ . As an alternative, you can add your stack's list to MONITOR= and it would do that for you!

**Comment by gotson** [comment]
It's weird because `portainer` is aware of a stack that was created outside itself, so the info must be available via the `docker.sock`, no ?

The problem with `MONITOR=` is that it's not dynamic, which was what i was looking for.
