### ISSUE TITLE
DRY_RUN flag

### ISSUE THREAD

**Issue by onedr0p** [pyouroboros/ouroboros#140]
Allow action to only be notified of image updates instead of updating them automatically.

Something like:

# Only Notify
**Type:** `Boolean`
**Command Line:** `-l, --only-notify`
**Environment Variable:** `ONLY_NOTIFY`
**Default:** `False`
**Example:** `-e ONLY_NOTIFY=true`

Pulls new image and notifies user of updates to an image

**Comment by tlkamp** [comment]
Thanks for the suggestion!

Would you prefer the notification as a one-off or something that ouroboros would monitor continuously?

I'm thinking it could be a `--dry-run` style argument, similar to `--run-once`, except it doesn't actually update.

**Comment by tlkamp** [comment]
I see where you're coming from, but ouroboros' purpose is to _update_ running containers. I'm not sure how I feel about this in-between, where it would download a new container but not update the running container.

I feel like a dry-run notification from ouroboros to the user about what it _would do_ would be a good compromise.

Is there something about your use case I'm not considering? I'd like to know more about it before deciding.

**Comment by DirtyCajunRice** [comment]
i do like the dry run idea regardless of the current question... i think we should look into that. As for the pull but dont update... its doable... i dont know if it really fits the scope though.

**Comment by tlkamp** [comment]
My biggest concern is the amount of space consumed on the host by download containers but not doing anything with them. At least when ouroboros updates, it cleans up after itself. This would consume space like crazy and never free it up. It sounds like more work in general for the end user.

**Comment by onedr0p** [comment]
Would there be a way with the Docker hub API to check if a new image is available without pulling it? If so that might be an option.

**Comment by DirtyCajunRice** [comment]
We do get the information before pulling the image. If the stop happened before the pull your issue wouldnt be an issue @tlkamp

**Comment by tlkamp** [comment]
@DirtyCajunRice correct, but the initial ask was that we download the new container but don't update the running one.

So, @onedr0p  - would a `--dry-run` option that notifies you what _would_ be updated (without actually downloading) be a good fit for your needs?

I see this as something we add anyway but I don't want to stray far from the reason you opened this issue.

**Comment by onedr0p** [comment]
@tlkamp that option sounds good to me!

**Comment by shadowking001** [comment]
+1 for this feature, it's something watchtower was missing and it could be nice to have it with ouroboros :)

**Comment by DirtyCajunRice** [comment]
Exists in develop :)
