### ISSUE TITLE
false isn't false?

### ISSUE THREAD

**Issue by scottjl** [pyouroboros/ouroboros#141]
- removed -

**Comment by circa10a** [comment]
By setting the boolean environment variables, enables them as `true` regardless of the value. The equivalent of false is just not setting the option.

**Comment by circa10a** [comment]
@DirtyCajunRice @tlkamp Think this is something we should spell out in the docs?

**Comment by tlkamp** [comment]
I think we could do better with the logging. We can update the docs but that's not going to fix an awkward log message like this.

**Comment by DirtyCajunRice** [comment]
i mean honestly... anything but true should be false. so i can make the logging better. It IS doing its job. just explained it... badly.

**Comment by tlkamp** [comment]
Why don't we allow `true`/`yes` like for the label value? It might be more consistent.

**Comment by DirtyCajunRice** [comment]
we do. thats what i meant with "anything other than true"

**Comment by scottjl** [comment]
I have a problem with this. I explicitly want this value as false so it is clearly stated for anyone reviewing this compose file, and should one day the default value be flipped to true I am not surprised with sudden updates to latest.

**Comment by DirtyCajunRice** [comment]
We are saying the same thing you are just differently.
if the value is true/yes, then update to latest.
if the value is false/no/poop/herpdederp/shamalamadingdong, then assume it is false. 

That sound reasonable?

**Comment by tlkamp** [comment]
I also prefer explicit over implicit. Here's my current thought: 

Honor true/yes and false/no, and anything other than those values is inferred as false and the logs are clear about which case this is.

**Comment by scottjl** [comment]
The behavior seems as expected, the error message is misleading. You should print that response if someone enters something other than true/false.

**Comment by DirtyCajunRice** [comment]
Right. thats what what needs modifying. Ill tag the issue # tonight when i update it.
