### ISSUE TITLE
updating containers without labels and LABEL_ENABLE set to true

### ISSUE THREAD

**Issue by scottjl** [pyouroboros/ouroboros#142]
- removed -

**Comment by DirtyCajunRice** [comment]
So there were a few points of contention about the way this was to be implemented. We chose a revised approach to what watchtower did.
* Our label is com.ouroboros.enable
* Enabling label-enable just gives label precedence over monitor/ignore
* Watchtower did not have monitor/ignore as a separate option so our logic required refining

The flow is as follows:
1. If label exists and it is true > monitor else
2. if label exists and is false > dont monitor else
3. if there is a monitor list and the container is in it and not in the ignore list > monitor else
4. if the container is not in the ignore list > monitor

This allows fallback to the monitor/ignore lists when no label is present. there will be more labels added in the coming days for other options (like dependency restarts), and will utilize the LABEL_ENABLE feature. It is not coupled to the monitor/ignore directly.

Summarized:   
We have, in our opinion, improved upon the very basic logic of labels only that watchtower implemented. This allows people with more docker knowledge to use labels, as well as people without to not. This also allows for leniency when labels are forgotten but implemented.

**Comment by scottjl** [comment]
this is, in my opinion, poor logic. ouroboros should err on the side of caution and make no changes unless explicitly instructed to do so. if no label is set. the container should be ignored. if someone has the docker knowledge to want to make use of LABEL_ENABLE then they should have the knowledge to explicitly set labels on containers permitting them to be updated, everything else should remain untouched. watchtower does no action unless told to do so with label monitoring enabled.

this alone is a deal breaker for me for using ouroborus.

**Comment by tlkamp** [comment]
This is the behavior as specified in the docs. We monitor _everything_ unless you specify what to (or what not to) monitor. If you're going to add the labels anyway, why is it a deal breaker?

**Comment by scottjl** [comment]
Note your wiki incorrectly states:

> If a container has a com.ouroboros.enable label, only watch it if it is set to true. Supersedes monitor/ignore in precedence.

https://github.com/pyouroboros/ouroboros/wiki/Usage#label-enable

This alone implies it will only watch the container if watch is set to true.

**Comment by scottjl** [comment]
> This is the behavior as specified in the docs. We monitor _everything_ unless you specify what to (or what not to) monitor. If you're going to add the labels anyway, why is it a deal breaker?

Because if I spin up an entirely new container that does not have a label set for ouro, then ouro should not touch that container.

Example, I have ouro monitoring a development server with a number of containers. A new developer comes on and spins up a container on that server but isn't aware of ouro and explicitly uses an older version of something, say mysql 5.6, ouro goes ahead and updates his container without his knowledge.

Ouro needs a mode where it makes no changes at all unless flagged to do so on containers, ignore all, upgrade only permitted. Blindly upgrading everything without regard is simply a bad practice.

**Comment by DirtyCajunRice** [comment]
having literally anything at all inside of MONITOR= achieves the desired result. In your circumstance, if 99% of your env has labels, and you have LABEL_ENABLE=true and MONITOR=fakecontainername, new containers spun up will not be monitored unless they have a label, or are named exactly “fakecontainername”

**Comment by scottjl** [comment]
So I basically have to set up a false case to prevent Ouroboros from causing potential harm. This is, again my opinion, completely backwards and something Watchtower does correctly. Take no action unless instructed to do so, and for me, is a dealbreaker.

I would advise that this behavior be very explicitly stated in the wiki so no one else is surprised. I'm glad I was testing this out on a development system first.

**Comment by DirtyCajunRice** [comment]
Just to be explicit, since this has turned into a frustrated finger pointing...

You have to set up a false case to have ouroboros, which has more logic in place than watchtower, act like watchtower. This is because you have watchtower as your basis of reference, and because watchtower logic was the *foundation* of Ouroboros logic. We have given you an answer that succinctly forces Ouroboros to behave exactly like watchtower. While it may be an "agree-to-disagree" situation, both our answer and ouroboros's logic play a part in what makes ouroboros different.

We appreciate the feedback regardless. I will make sure the wiki is as explicit as possible for this flag.

**Comment by DirtyCajunRice** [comment]
Just so you are in the loop, We are talking privately in discord about finding some sort of middle ground (possibly an additional flag e.g. --labels-only). One way or another, ill update here :)

**Comment by scottjl** [comment]
i'm not trying to finger point anything. what i am trying to do is keep people who fire up your software from being surprised as i was. in the end any software should follow the rule "do no harm" or maybe "do no unexpected behavior". regardless of my prior experience with watchtower, from the documentation itself, it leads me to believe, with LABEL_ENABLED that only containers set to true would be updated, that clearly isn't the case. I understand there's a fall-through with your logic and to also upgrade anything without a label. My case is this logic is faulty. LABEL_ENABLED should rely strictly then on labels being set to true, or set to false, or note set at all which would also be taken as false (just as the case of LATEST being anything except strictly true) and any logic behind MONITOR and IGNORE disregarded. You're trying to use both systems which is confusing at best and caused me unexpected behavior. Why would someone want to use both systems at the same time? Labels give me fine-tune control, regardless of container names. The previous suggestion to use a "fakecontainername" is poor because someone could still end up using it and it relies on a bad trick of the system to get desired behavior.

Not trying to finger-point or cause an argument. Just pointing out that the behavior may catch someone off-guard and cause a serious issue for them. Unexpected behaviors should simply be avoided. Maybe change the logic, or maybe very clearly point this out in the documentation, as it was unclear to me.
