### ISSUE TITLE
MS teams notification 

### ISSUE THREAD

**Issue by ThomasRunting** [pyouroboros/ouroboros#143]
Can you add ms teams as a notification end point. The watchtower branch supports it.

**Comment by DirtyCajunRice** [comment]
this is already implicitly an option under the “Generic” webhook. In microsoft teams, if you set your incoming connector to webook, and add the webook to your list of webhooks and viola!

**Comment by ThomasRunting** [comment]
Ill give it a go.
I did ask this because the wiki hasn't got ms teams as a supported webhook endpoint.
