### ISSUE TITLE
Docker container logging issues

### ISSUE THREAD

**Issue by raman325** [pyouroboros/ouroboros#147]
Hi there,

Thanks for the great documentation, and for the most part, Ouroboros worked great! Unfortunately, Ouroboros terminated early during my first update. I'm running in Run Once mode with the rm flag to clean up the container on exit, so I wasn't able to look at the logs to see what happened (I did notice that one of my containers was updated but failed to start - this correlates with when Ouroboros terminated. I deleted the container and reran it using the same configuration without issue). This leads me to a couple of comments/requests:

1. Ideally I'd like to mount a volume that I can persist the Ouroboros logs in to help me troubleshoot future issues. Currently Ouroboros logs to std-out and std-err, is it possible to add a flag/environment variable to do that?
2. I noticed in the Wiki that no default value is stated for the log level. What is the default value?
3. I noticed when I was checking docker logs during the first run that the timestamps didn't match the timezone I had set. I configure the timezone in all of my containers and haven't seen this issue before so I'm wondering what's different for this container.

Thanks!

**Comment by DirtyCajunRice** [comment]
1. docker logs this to docker log driver. you can change the driver to something else and choose to save those logs however you see fit! 
2. default is info. we can update that.
3. if you have TZ= you should have accurate info. can you show us relevant logging output thats incorrect and your config?

**Comment by DirtyCajunRice** [comment]
I have updated the wiki to show default= `info`
Still need more information on 3 :)

**Comment by raman325** [comment]
1. This is my first time looking at docker log drivers, so my knowledge is extremely limited, but based on the documentation it seems like the only alternative to the standard json-file driver is to use a driver that sends the logs to a log aggregator. In my case, I think can use the syslog driver, but this seems like a lot of potential work for someone who's running a couple of containers to manage some apps for the home and who may not have additional log infrastructure set up - I know that when I first started migrating my self-hosted applications to Docker, this would have gone over my head. Not sure what the best solution is to that but just something to think about.
2. Awesome, appreciate it!
3. I just tried again and they match. I could have sworn they weren't last night, but in either case, I guess this is resolved.

Thanks for the quick response! If I am able to replicate the behavior that triggered this conversation (ouroboros terminating early), I will let you know.

**Comment by DirtyCajunRice** [comment]
Wonderful!. Logging to file is not hard, just not very docker-esque for this situation. I am talking it over with the other devs. If the consensus is to add a file logger i will absolutely re-open this and use it as the bug. Thanks for the feedback!
