### ISSUE TITLE
Docker TLS over TCP connections

### ISSUE THREAD

**Issue by nmcfaul** [pyouroboros/ouroboros#154]
When connecting to docker over TCP using TLS, docker server authenticates the client using a provided client certificate.

With watchtower, this was achieved through specifying the DOCKER_CERT_PATH which would contain the client cert, client key and the ca cert.  i.e. {ca,cert,key}.pem in the default $HOME/.docker directory.  I assumed given the configuration documented at https://github.com/pyouroboros/ouroboros/wiki/Usage#docker-tls-verify that the behaviour would be similar with ouroboros. This is not the case, and ouroboros does not read in client certificates.

**Comment by DirtyCajunRice** [comment]
Were you mounting it as a volume? or as an env var? (I currently have it designed for volumes.)

**Comment by nmcfaul** [comment]
I've tried both; mounting of the TLS client cert file directory with {ca,cert,key}.pem files into /root/.docker directory (as per docs) as well as setting DOCKER_CERT_PATH, and mounting to an arbitrary directory and also setting DOCKER_CERT_PATH, neither work.

I suspect this may lie in the fact that ouroboros is designed to connect to multiple docker daemons and watch for events, which means the DockerClient is instantiated manually rather than reading the environment configuration for DOCKER_HOST, DOCKER_TLS_VERIFY and DOCKER_CERT_PATH - this method though also needs to support multiple TLS configurations for any remote docker daemon that has been protected by mutual TLS.

**Comment by DirtyCajunRice** [comment]
I see what you are saying. I think i could build it in such a way that if you named your files {socket_name}-{ca,cert,key}.pem it could read from each with that template and a flag enabled. Thoughts?

**Comment by nmcfaul** [comment]
That would work, though it may be ideal to follow an existing pattern defined by docker. The configuration defined here https://docs.docker.com/engine/security/certificates/ is used to authenticate a docker engine to a registry using mTLS.

if you define a docker socket as `tcp://<ip address|hostname>:2376` an example structure could be;

```
<base path>/certs.d/
-- <ipaddress|hostname>:2376/
    -- client-cert.pem|cert.pem|client.cert
    -- client-key.pem|key.pem|client.key
    -- ca.pem|ca.crt
```
`<base path>` would (ideally) be a bind mount. Personally I find this would be the most flexible.

**Comment by DirtyCajunRice** [comment]
Per the above commit, I have implemented this. It should be in develop by tonight. Because of the non-docker.py structure being more strict, i followed that structure and it will be as follows:
```
   /etc/docker/certs.d/        <-- Certificate directory
    └── localhost:5000          <-- socket as defined in config after //
       ├── client.cert          <-- Client certificate
       ├── client.key           <-- Client key
       └── ca.crt               <-- CA certificate
```
and would be mounted something like
```
-v /etc/docker/certs.d:/etc/docker/certs.d
```

**Comment by DirtyCajunRice** [comment]
merged to develop :>
