### ISSUE TITLE
Support for addding an identifier (hostname?) to notifications

### ISSUE THREAD

**Issue by Adam-Ant** [pyouroboros/ouroboros#158]
I currently manage around 15 hosts with Watchtower, and one thing that it has over Ouroboros is the ability to add an identifier to the notifications. For example, if I have the same image update on three hosts running Ouroboros, I currently have no way of telling which message comes from which instance, short of a seperate bot and webhook for each host. Watchtower gets around this issue by adding the container hostname to each message, as below:
![190127-234615](https://user-images.githubusercontent.com/9141670/51808587-c3124b80-228d-11e9-82b9-138ba16e1c58.png)

I'm not sure if hostname is the correct call for an identifier, or simply a config option, but either would make deploying Ouroboros at scale a lot easier. Thanks.

**Comment by circa10a** [comment]
Ouroboros does this currently by mentioning what docker socket was used to make the update. Whether that is a `unix:///var/run/docker.sock` or `tcp://<hostname>:2375` or `tcp://<ip>:2365`

Example:

![alt text](https://images-ext-1.discordapp.net/external/tKxB0xr6xr-vBIUzTWZW-e2U8tNRlekwI00KkANWEy0/https/bin.cajun.pro/images/DiscordCanary_1ZjgDxjQFF.png)

**Comment by Adam-Ant** [comment]
Interesting, the sock remapping is a good work around for now, thank you. I'll be honest, im still using watchtower at the moment, it'll take me a day or two to test and build the changes into my puppet infrastructure anyways, so I'll wait at this point. Thanks very much for the quick response on this though!

**Comment by DirtyCajunRice** [comment]
Fixed in develop :)
