### ISSUE TITLE
Feature suggestion: Add URL to notifications

### ISSUE THREAD

**Issue by cybermcm** [pyouroboros/ouroboros#165]
First of all, thank you for your time and your great product (switched from Watchtower).

Another suggestion: Currently I do a quick test after an automatic update to ensure that everything works as expected. Most of my containers are reachable via web, a quick check of the webpage is normally enough.
My idea: another (possible) ouroboros label for every conainer containing an URL. This URL is then included in the notification so that a single click is sufficient to get to the containers webinterface.
Would save some time...

**Comment by DirtyCajunRice** [comment]
i feel like this should be automated outside of ouroboros. I totally feel your frustration, im just not certain that is is “in scope”. Have you thought about making a flow in node-red? would be easy enough to make a webook endpoint, get the name of the container(s) from the body text, and do a 200 response code check on the url that matches that container in a dict

**Comment by cybermcm** [comment]
I never used node-red before, seems interesting... Of course I could implement a monitoring system to watch my webservers. But this would be an overkill in my point of view for my containers.
Maybe my first post was not clear enough, I don't want ouroboros to do anything active, I just want to enrich the notification mail with a self defined parameter (URL).

**Comment by DirtyCajunRice** [comment]
The issue with that, is that container URLs are a super specific use case that im not sure would add much value to most people. In addition, notifications are plain-text as not all endpoints support links so it would have to be its own line item. Im going to talk it over with the devs to get their opinion but I believe that Docker Health Checks or an outside check would probably be better.

**Comment by circa10a** [comment]
Im going to agree with @DirtyCajunRice , there are many different ways to handle this and I don't think it's ouroboros' place to do so.

**Comment by cybermcm** [comment]
OK for me... If automation is my goal I really shouldn't monitor updates manually by clicking on links. I'll close this issue.
