### ISSUE TITLE
Ouroboros does not respect MONITOR=

### ISSUE THREAD

**Issue by Nicholaiii** [pyouroboros/ouroboros#166]
Using env vars REPO_USER and REPO_PASS I'm having trouble authenticating in Ouroboros.
I took a look at config.py, are you sure [these](https://github.com/pyouroboros/ouroboros/pull/79/commits/6fce80fa497cbb14698e4444ae21de1ecf68baa9#diff-4e9c24a21fc5c692f59ed0b7ada103fcR80) are supposed to be capital first letter? The Docker SDK specifies "username" and "password", but I have 0 practical experience, so if I'm doing something wrong, please give me a suggestion for a fix.

**Comment by DirtyCajunRice** [comment]
this is a configuration error. please jump in discord for support :)

**Comment by DirtyCajunRice** [comment]
From discord: With debug on, it was trying to authenticate to something not in the monitored list. Bug. Adding to develop shortly

**Comment by DirtyCajunRice** [comment]
fixed in develop :)
