### ISSUE TITLE
Exception when trying to update container with complex compose networks

### ISSUE THREAD

**Issue by frebib** [pyouroboros/ouroboros#196]
Whilst testing the latest improvement to networking on the develop branch, I observed this error  
```
2019-02-09 23:47:45 : INFO : dockerclient : media_plex_1 will be updated
2019-02-09 23:47:48 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-09 23:52:41 GMT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/networks/media_backend/connect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 270, in update
    ipv6_address=container.attrs['NetworkSettings']['Networks'][network]['GlobalIPv6Address']
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 248, in connect_container_to_network
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("user specified IP address is supported only when connecting to networks with user configured subnets")
```

docker-compose.yml:
```yaml
services:
  plex:
<snip>
    hostname: plex.domain.name
    networks:
      public:
        ipv4_address: '000.000.105.4'
        ipv6_address: 'ffff:ffff:ffff:9::4'
      backend:
        aliases:
        - plex.domain.name
    restart: unless-stopped

networks:
  backend:
  public:
    external: true
```

Both networks are bridge networks, defined with no strange arguments. The `public` network is defined as follows:
`docker network create --ipv6 --attachable --driver bridge --subnet 000.000.105.0/24 --gateway 000.000.105.1 --subnet ffff:ffff:ffff:9::/64 --gateway ffff:ffff:ffff:9::1 public`

**Comment by DirtyCajunRice** [comment]
looks like an ipv6 specific issue.

**Comment by frebib** [comment]
I'm happy to test with any device builds you may want to throw at me

**Comment by DirtyCajunRice** [comment]
can you try specifying your subnet as well in your compose? it looks like this is intended per https://github.com/moby/moby/issues/20547

**Comment by frebib** [comment]
Specifying addresses with the CIDR is invalid according to docker/compose. It is recognised as an invalid IP address

**Comment by DirtyCajunRice** [comment]
hmmm... can i get the output of docker network inspect public

**Comment by nightvisi0n** [comment]
`docker inspect plex` might also be useful here..

**Comment by nightvisi0n** [comment]
@frebib Is the IPv6 network link-local or global?  
Might be an issue with `link_local_ips` vs. `ipv6_address` in [connect_container_to_network](https://docker-py.readthedocs.io/en/stable/api.html#networks)

**Comment by frebib** [comment]
It's a global address. Inspect output pending

**Comment by frebib** [comment]
container: https://gist.githubusercontent.com/frebib/1a053cb894603a7fed246180ed445b5c/raw/db4a8a2c57a53c3bd068f3c682d9a94cdd76dda6/media_plex_1.json
network: https://gist.githubusercontent.com/frebib/da8479788e3042b6f8a33146bb745bc5/raw/eff899b1a9fbc47eb0e83a97ed0e3bc7c33be35c/public.json

I've snipped some unrelated information out but lmk if there is anything missing

**Comment by frebib** [comment]
Out of curiosity, I checked the code from Watchtower for comparison and it appears the Go library for connecting a container to a network takes the entire network object, encodes it, and posts it to the Docker daemon. I'm not sure why the Python library differs in that regard

**Comment by frebib** [comment]
https://github.com/docker/go-docker/blob/4daae26030ad00e348edddff9767924ae57a3b82/network_connect.go#L11-L15
https://github.com/docker/go-docker/blob/4daae26030ad00e348edddff9767924ae57a3b82/request.go#L41-L46

**Comment by frebib** [comment]
I've reverse-engineered the go-docker library and implemented the same functionality directly into ouroboros. Admittedly it's a hack, but it seems to work

```diff
diff --git a/pyouroboros/dockerclient.py b/pyouroboros/dockerclient.py
index a57bda9..230186c 100644
--- a/pyouroboros/dockerclient.py
+++ b/pyouroboros/dockerclient.py
@@ -250,25 +250,26 @@ class Container(object):
                 # connect the new container to all networks of the old container
                 for network in container.attrs['NetworkSettings']['Networks']:
                     host_net = self.client.networks.get(network_id=network)
+                    net_obj = container.attrs['NetworkSettings']['Networks'][network]
                     if host_net.attrs.get('Options', {}).get('com.docker.network.bridge.default_bridge') == 'true':
                         # default network
                         # User specified IP address is supported on user defined networks only
                         self.client.api.connect_container_to_network(
                             container=new_container.attrs['Id'],
                             net_id=network,
-                            aliases=container.attrs['NetworkSettings']['Networks'][network]['Aliases'],
-                            links=container.attrs['NetworkSettings']['Networks'][network]['Links']
+                            aliases=net_obj['Aliases'],
+                            links=net_obj['Links']
                         )
                     else:
                         # user defined network
-                        self.client.api.connect_container_to_network(
-                            container=new_container.attrs['Id'],
-                            net_id=network,
-                            aliases=container.attrs['NetworkSettings']['Networks'][network]['Aliases'],
-                            links=container.attrs['NetworkSettings']['Networks'][network]['Links'],
-                            ipv4_address=container.attrs['NetworkSettings']['Networks'][network]['IPAddress'],
-                            ipv6_address=container.attrs['NetworkSettings']['Networks'][network]['GlobalIPv6Address']
-                        )
+                        data = {
+                                "Container": new_container.attrs['Id'],
+                                "EndpointConfig": net_obj,
+                                }
+
+                        url = self.client.api._url("/networks/{0}/connect", network)
+                        res = self.client.api._post_json(url, data=data)
+                        self.client.api._raise_for_status(res)
 
                 new_container.start()
 
```

**Comment by nightvisi0n** [comment]
After some debugging I can say, that this is not an issue because of IPv6 and neither because of the different implementation of the docker-py library comparing to the go version.  
I simple made a mistake in differentiating when to carry-over the IPv4/6 addresses. I only looked at the `com.docker.network.bridge.default_bridge` label, but of course all user defined networks (without a subnet assigned) are lacking this label. Thus the current implementation assumed it's a network with a user defined subnet (which is wrong). 

@frebib I pushed a fix to my fork, would be great if you could test whether it fixes this error: `sudo docker build -t ouroboros:local-build https://github.com/nightvisi0n/ouroboros.git#fix_user-defined-network-detection`.  
I will create a PR afterwards.

**Comment by DirtyCajunRice** [comment]
ill keep my eyes peeled for that PR ;)

**Comment by DirtyCajunRice** [comment]
above merge fixes this one. Closing
