### ISSUE TITLE
Containers relying upon network namespace of a container that gets updated breaks when the parent container is recreated

### ISSUE THREAD

**Issue by frebib** [pyouroboros/ouroboros#197]
I have two containers, p (parent) and c (child), where `c.NetworkMode="container:<parent-container-id>`
When p gets updated by ouroboros, the child container points at a now invalid network namespace.
In this scenario I would expect the child container, c, to also get recreated, after the parent has been replaced.

The equivalent docker-compose to recreate this is:
```yaml
services:
  parent:
    image: whatever
  child:
    image: whatever:also
    network_mode: service:parent
```

The `docker inspect` output for the child container resembles the following:
```
[
    {
        "Name": "/project_child_1",
        "HostConfig": {
            "NetworkMode": "container:4ed997b652503ed38d6465f742424e34b9eb6329811b0714e89aa96446dd2984",
            "PortBindings": {},
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]
```

**Comment by circa10a** [comment]
There were some recent networking improvements made on our develop branch. Could you try using our `-develop` tag to see if that fixes your issue?

**Comment by DirtyCajunRice** [comment]
This is the first time I’ve seen this used in the wild haha. Since you are in a docker-compose file, and it is a docker-compose only option, what is the real benefit over specifying the networks? Docker has no intention of allowing a docker-compose api and we would have to essentially rebuild the functionality of this from  docker-compose into ouroboros which I’m not sure we want to do. It puts a lot of tricky things in place... sanity... order... reference... relevance... allowance... etc.

**Comment by frebib** [comment]
It is a standard docker feature, see https://docs.docker.com/engine/reference/run/#network-settings

I find it useful because it allows me to bind two containers ports to a single IP address.

Annoyingly there is nothing to identify dependent containers from the parent container, afaik, so it would require checking all containers if they are parented

**Comment by frebib** [comment]
This functionality is similar to the `depends-on` flag in the sense that it will update dependent containers, except matching on the network namespace.

**Comment by DirtyCajunRice** [comment]
So initial thoughts on this deployment would revolve around iterating the list multiple times. once to find all updates and save that list with a sublist of "dependants". then again to create a unique set() of the dependants and send sigterm, then again to update containers, then again to turn depedants back on.

**Comment by DirtyCajunRice** [comment]
can you test the patch/group-5 branch using hard_depends_on label?

**Comment by frebib** [comment]
Damn you're on-it.
I'll try it as soon as I get enough time to play with it. I like the idea of the `hard_depends_on`, it's a good solution. It would be nice to automatically detect the container dependency and infer the hard dependency but the label will do for now :)

**Comment by DirtyCajunRice** [comment]
Im going to pre-emptively close this out as i _think_ its resolved with all of whats merged into develop. If it ends up still having issues let me know and ill re open :)
