### ISSUE TITLE
Change depends_on logic

### ISSUE THREAD

**Issue by KopfKrieg** [pyouroboros/ouroboros#198]
I've recently switched from watchtower to ouroboros on my test server and unfortunately, ouroboros breaks a lot of services when updating containers. I define all my services through compose files, and I've got a caddy webserver working as proxy for most of my services.

So, my layout is usually something like:
```
Caddy <-> network "proxy" <-> Nextcloud <-> network "backend" <-> PostgreSQL
      <-> network "proxy" <-> Matomo <-> network "backend" <-> MariaDB
```

Ouroboros stops for example the PostgreSQL container, updates it, and recreates it, but doesn't stop Nextcloud. Nextcloud is defined with "depends_on: PostgreSQL" in my docker-compose file, so not sure why this happens. AFAIK Nextcloud should be stopped too.

Best would be to stop all services in a stack ("stack" is defined here as all services defined in a compose file), then updating the necessary containers (recreate them), and then starting the whole stack again (docker-compose up -d equivalent).

I also get gateway errors in Caddy if, for example, Nextcloud is updated.

Also, stopping a stack and restarting didn't help in any of the cases, I've had to completely recreate all container in a stack, then starting it. Otherwise I'd have connection errors :/

Is this a known issue?

**Comment by circa10a** [comment]
Ouroboros currently doesn't support `depends_on` for a couple of reasons. The main one being that docker.py doesn't support this or anything via compose.

For the network configuration, there were some recent improvements made on our develop branch. Could you try using our `-develop` tag?

**Comment by DirtyCajunRice** [comment]
@circa10a we do have a com.ouroboros.depends-on label that sort of adds this functionality, but it is not the root issue here.
@KopfKrieg I dont know caddy but nginx uses a resolver that caches on load. Changes needed to be made to the nginx resolver to allow a more “dynamic” resolution of docker IPs

**Comment by KopfKrieg** [comment]
@circa10a I'll test the develop branch, it hopefully fixes the network problems. I'd also like to mention I don't support your statement that "containers should run independently" for two reasons:
 - My services already run independently, but (e.g.) Nextcloud still needs a database in the background. That's why I'm using docker-compose files, to group them together. Of course you can restart the database without issues, but if you're updating the database, Nextcloud should still be shut off in the meantime
 - Ouroboros broke the services in a way a simple restart couldn't fix. Something went horribly wrong there, and I don't know what. Docker is there to prevent exactly that, and somehow it didn't work. Monitoring got it, but restarting as mentioned before didn't fix it. That should never happen (and, in fact, did never happen with watchtower)

@DirtyCajunRice Caddy usually works very nice with docker (like Traefik does), I really haven't had any issues with it until I've switched to ouroboros as update mechanism. Caddy's also able to watch the docker socket for updates.

**Comment by DirtyCajunRice** [comment]
Please test develop for me and see if recent changes have resolved this for you

**Comment by KopfKrieg** [comment]
Wow, that was fast. I'm already using the develop-image, so it's just a matter of time (I need to wait until a container gets updated…).

**Comment by DirtyCajunRice** [comment]
be aware that `com.ouroboros.depends-on` was changed to `com.ouroboros.depends_on` to align with our other labels. (if you need to make any changes to your label definitions)

**Comment by DirtyCajunRice** [comment]
going to close this out as its in develop. If you find there are still issues please let me know and ill re-open

**Comment by KopfKrieg** [comment]
I've had a few container updates the last few hours, all went fine. Seems good to me. I'll let you know if it doesn't work anymore :D

**Comment by DirtyCajunRice** [comment]
awesome!

**Comment by KopfKrieg** [comment]
Oh, and thank you, by the way :)
