### ISSUE TITLE
AttributeError: 'list' object has no attribute 'id'

### ISSUE THREAD

**Issue by tedrock** [pyouroboros/ouroboros#210]
Version: 1.2.0-master
Running in a docker container using docker compose
Running on Debian

`2019-02-13 22:52:58 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-02-13 22:52:45 EST], next run at: 2019-02-13 22:52:45 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 275, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 240, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'list' object has no attribute 'id'`

**Comment by tedrock** [comment]
In case you're curious, the configuration I'm using:
services
  ouroboros:
    image: pyouroboros/ouroboros
    container_name: ouroboros
    environment:
      - TZ=America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --self-update --interval 300 --log-level info --cleanup -N 'slack:///*****/#*******'

**Comment by DirtyCajunRice** [comment]
I found it. We just did a major refactor and removed some extra code. In doing so I didnt account for if someone didnt specify a tag at all e.g. asdf/asdf without asdf/asdf:asdf. Ive added the simple fix in the push above. As this is critical im going to make sure we merge it asap

**Comment by DirtyCajunRice** [comment]
In develop now. going to master

**Comment by tedrock** [comment]
Out of curiosity, where should I have had this tag that I was missing?

**Comment by DirtyCajunRice** [comment]
no you shouldnt _NEED_ a tag. It was my fault. I jsut didnt test without it. not putting a tag is implicitly putting :latest as far as docker is concerned

**Comment by DirtyCajunRice** [comment]
Its fixed in master. Good call
