### ISSUE TITLE
Issue with Swarm Mode V2

### ISSUE THREAD

**Issue by computeralex92** [pyouroboros/ouroboros#216]
While testing for resolving #178, i found the reason why there is a issue with the services created by ouroboros:

If a service was updated with the docker cli, the inspect of a container shows this image config:
`"Image": "nginx:stable-alpine@sha256:b96aeeb1687703c49096f4969358d44f8520b671da94848309a3ba5be5b4c632",`

With this config, ouroboros wants to update the container but there is no newer image.
If you run the update, it replace the container with the same image.

The same container created by ouroboros have this image config:
`"Image": "nginx:stable-alpine",`

After that, ouroboros skip the containers because it is not able to find the SHA of the image.
The needed SHA is in both cases shown as part of the inspect, but not as a part of the config.

`"Image": "sha256:66952fd0a8efa0598626fad89d3a0827bc24fc92c3adb576adbc9fd58606e1af",`

I added both inspects to Gist:
https://gist.github.com/computeralex92/2f93cd64656850b2d2d08970c6d21b1a
https://gist.github.com/computeralex92/43ea1953d256324ef7caa0e5711df9bf

**Comment by DirtyCajunRice** [comment]
I cant seem to find a way to get the image key from a service through docker.py but maybe @tlkamp or @circa10a  can see something i dont

**Comment by circa10a** [comment]
I'll take a stab

**Comment by circa10a** [comment]
@DirtyCajunRice 
did you try the low level API client?

```python
from docker import APIClient
client = APIClient(base_url='unix://var/run/docker.sock')
for service in client.services():
    service_name = service['Spec']['Name']
    service_image = client.inspect_service(service=service_name)['Spec']['TaskTemplate']['ContainerSpec']['Image']
    print(service_image)
# Output
# circa10a/nginx-wget:alpine@sha256:8dedb3f893f1c4d63125ea3d74e18d9980ecafc61ddb9cff21b97fae87020666
```

**Comment by DirtyCajunRice** [comment]
@circa10a thats literally what we are already doing without the low level. What we need is the equivalent of `service['Image']` Which does not exist.

**Comment by DirtyCajunRice** [comment]
as another way to look at it he is saying it tries to update something that doesnt need updating, which is odd since its checking the sha when it DOES exist initially. Maybe the root can be found there

**Comment by DirtyCajunRice** [comment]
> With this config, ouroboros wants to update the container but there is no newer image.
If you run the update, it replace the container with the same image.

This is what we need to get to the bottom of

**Comment by DirtyCajunRice** [comment]
Should be fixed in develop
