### ISSUE TITLE
CRON job Running exactly 24 hours later than scheduled

### ISSUE THREAD

**Issue by shadowking001** [pyouroboros/ouroboros#231]
Hello,

I'm facing issues with the CRON scheduling option.
Here is my container setup :

> docker create \
> --name=ouroboros \
> --restart=unless-stopped \
> -v /var/run/docker.sock:/var/run/docker.sock \
> -e TZ=Europe/Brussels \
> -e SELF_UPDATE="true" \
> -e LABEL_ENABLE="true" \
> -e LABELS_ONLY="true" \
> -e CLEANUP="true" \
> -e CRON="30 12 * * 4" \
> pyouroboros/ouroboros:latest

The container is in bridge network mode.
On a side note, I added the label com.ouroboros.enable to every container I'd like to monitor.
Here are the living logs of the runnning container :

`2019-02-21 12:14:00 : INFO : ouroboros : Version: 1.2.1-master,
2019-02-21 12:14:00 : INFO : config : Cron configuration is valid. Using Cron schedule ['30', '12', '*', '*', '4']`

The container should have, to my understanding, started its updating process 16 minutes later.
I could use the --interval command but I'd rather get CRON working in a first time.
I'm running it on a **Synology DS218+** with DSM 6.2 Update 4 (up-to-date).

Thanks for your help !

**Comment by DirtyCajunRice** [comment]
it should show you in those same logs a next_run. Can I get that as well?

**Comment by shadowking001** [comment]
Unfortunetaly, I got nothing else to give you, because that's the sole output I get.
Right now I tried again : 

![image](https://user-images.githubusercontent.com/43928955/53201407-3ce6ec00-3624-11e9-90b8-8e383a43c826.png)

It's two past 10pm right now, and still nothing else in the logs.

Or maybe I dont look at the right place...?

**Comment by DirtyCajunRice** [comment]
ah. turn on debug logging please

**Comment by shadowking001** [comment]
Here we go :

> 2019-02-22 07:22:26 : INFO : ouroboros : Version: 1.2.1-master,
> 2019-02-22 07:22:26 : INFO : config : Cron configuration is valid. Using Cron schedule ['30', '4', '*', '*', '6'],
> 2019-02-22 07:22:26 : DEBUG : ouroboros : Ouroboros configuration: {'interval': None, 'docker_sockets': ['unix://var/run/docker.sock'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'cleanup': True, 'cron': ['30', '4', '*', '*', '6'], 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'self_update': True, 'label_enable': True, 'labels_only': True, 'hostname': 'cb6a0f00b382', 'docker_tls_verify': True},
> 2019-02-22 07:22:26 : INFO : base : Scheduler started,
> 2019-02-22 07:22:26 : DEBUG : base : Looking for jobs to run,
> 2019-02-22 07:22:26 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'],
> 2019-02-22 07:22:26 : DEBUG : config : No config file found,
> 2019-02-22 07:22:26 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'],
> 2019-02-22 07:22:26 : DEBUG : config : No config file found,
> 2019-02-22 07:22:26 : DEBUG : base : No jobs; waiting until a job is added,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22status%22%3A+%5B%22running%22%5D%7D HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/cb6a0f00b382263b1c9ee8a0d0de7f69b809b320608d0076aac2cc361ecf3946/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/bac370ca9d09772d14e6572dd50dfa54523b67e25c0ac970e43f316e02da6422/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/e762e62ed352461c0cad38dec05a6147c249f4dd20f33b34d00a16d76e2d0132/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/f8c7706bd7fccf0b22336eaa93769a4f20c5f734b5a3df638de1cf7eb4667a7a/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/021922ee91a2af47acb5cfc536ce9671936e5f83564c6e2e1797376e0c326b02/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/a34fe0c95ebcc60acbc8d6002181bd16ae9b17d7702a231447f452c099eaf759/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/4ce30c12edd0304531c4aeba2aadfa259322f6c502a7fe7c8ffa774363e1f20a/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/3844feab1d3300085791edf4048f861874eec9c98cf13531213a9aef2b149205/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/c8ac6227a5ade717b3371a3e37c2290a1d897f11a5f1d11f9fbff1dc57110358/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/4254e7612508bf24e79ae33fced7000eb3bef0d44472121e5bd6b4297c317b6d/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/6de353cd2780a212122f08412842a173d29f550ea5992b3244a755e795e10638/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/bf7128a04b9dd97d5335d35bfa82711647810fab952a7b2145eb020e00b9ab63/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/5c8c63aea2d7380aa68d5e0ebb2065644082309042def3090b0f001033069a0c/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/ccf47f1ef1e3ae4c51e49fc3860578774e2736dd770ae3227ee3c3dfa654ed71/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/d7702b3b48f0e97776901b188e9dfd6f55d7cbce3229990896152217c1cff178/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/6ad5f6da46e0e2509594953d1104bb690975699125ab483bd39103cb1288a357/json HTTP/1.1" 200 None,
> 2019-02-22 07:22:26 : INFO : base : Added job "Cron container update for ********unix://********.sock" to job store "default",
> 2019-02-22 07:22:26 : DEBUG : base : Looking for jobs to run,
> 2019-02-22 07:22:26 : DEBUG : base : Next wakeup is due at 2019-02-24 04:30:00+01:00 (in 162453.181322 seconds)

My setup :

> docker create
> --name=ouroboros
> --restart=unless-stopped
> -v /var/run/docker.sock:/var/run/docker.sock
> -e TZ=Europe/Brussels
> -e LABEL_ENABLE=true
> -e LABELS_ONLY=true
> -e CLEANUP=true
> -e SELF_UPDATE=true
> -e LOG_LEVEL=debug
> -e CRON="30 4 * * 6"
> pyouroboros/ouroboros:latest

Seems like he adds a day to the scheduled time... next wakeup should have occured 2019-02-23 (saturday) instead of 24...

Thanks a lot

**Comment by circa10a** [comment]
@shadowking001 can you try using the `develop` tag?
we recently made a small configuration change to the cron scheduling component.

**Comment by shadowking001** [comment]
I tried with the `develop` tag but the behaviour was the same.
Then I scheduled it for yesterday 3 minutes ahead, and it told me the next wakeup would be occuring in 3 minutes... This way everything went fine.
By the way I checked the container's date with `docker exec -it ouroboros date` and it gave me the correct date, so I dont know why it behaved this way.

**Comment by DirtyCajunRice** [comment]
I cannot recreate this at all.

**Comment by shadowking001** [comment]
I can provide you whatever you need but I'm not an IT so I'll need some guidance.

**Comment by DirtyCajunRice** [comment]
Ive tried this on a UTC machine and on a localized TZ config and cannot reproduce. Im going to chalk this up to magic.

**Comment by mammo0** [comment]
same issue here...
I've set the CRON variable to "0 0 * * 0" (should run every Sunday at 0:00). But actually runs on Monday at 0:00. As a workaround I set the variable to "0 0 * * 6" and it works now. But no idea why this is happening... Basically the same logs as above.

PS: I've set the TZ variable to Europe/Berlin.

**Comment by DirtyCajunRice** [comment]
ive found the related information. sunday must be 7 not 0 https://github.com/agronholm/apscheduler/issues/349#issuecomment-475265326

**Comment by mammo0** [comment]
Ah ok thanks for the information!
So apscheduler is the culprit... Because it interprets the cron string not as crontab... I just copied the above string from another crontab job that runs on my server also on 0:00 every sunday.

Maybe you mention this in your Wiki that theirs another interpretation for the cron syntax.
