### ISSUE TITLE
Suggestion, move docs from wiki to repository

### ISSUE THREAD

**Issue by mathcantin** [pyouroboros/ouroboros#232]
Hi,
I find interesting the Github Wiki, but there are two big limitations:

1. It's not versioning with the code
2. It's not possible to submit pull request for it

My suggestion is to copy existing documentation from wiki to a folder docs. A link like https://github.com/pyouroboros/ouroboros/blob/master/docs/index.md will done the master branch documentation and a link like https://github.com/pyouroboros/ouroboros/blob/1.3.0/docs/index.md is the documentation for the version 1.3.0.

**Comment by DirtyCajunRice** [comment]
I dont want to abstract the docs to their own repo. Documentation updates can be done by any project maintainer. I personally feel making a documentation change request or making enough meaningful edits to the repository to become a project member is the right avenue here. @circa10a @tlkamp  thoughts?

**Comment by circa10a** [comment]
I agree @DirtyCajunRice. I prefer the wiki. Especially when clarifications need to be added on the fly, as we've seen is a common occurrence in the past.

**Comment by circa10a** [comment]
Maintainers have mutual agreement to keep the wiki. But we do appreciate the engagement and feedback.
