### ISSUE TITLE
Mail notification attributes not working

### ISSUE THREAD

**Issue by frumpymoons** [pyouroboros/ouroboros#251]
It seems like my attributes are getting ignored.

These are my values:
FROM: admin@example.com
TO: test@example.com
SMTP: smtp.example2.com
USER: admin@example.com
PASS: mypass

Here is my compose config

```  
ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - CRON="5 4 * * *"
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=Europe/Berlin
      - NOTIFIERS="mailtos://admin@example.com?user=admin@example.com&pass=mypass?smtp=smtp.example2.com?to=test@example.com"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

In the debug logs you can see most of the stuff gets ignored
```
2019-03-03 02:56:20 : DEBUG : NotifyEmail : Email From: admin@example.com <Ouroboros>
2019-03-03 02:56:20 : DEBUG : NotifyEmail : Email To: admin@example.com
2019-03-03 02:56:20 : DEBUG : NotifyEmail : Login ID: admin
2019-03-03 02:56:20 : DEBUG : NotifyEmail : Delivery: example.com:587
2019-03-03 02:56:20 : DEBUG : NotifyEmail : Connecting to remote SMTP server...
```

**Comment by caronc** [comment]
You're URL syntax is incorrect; you only use the question mark (**?**) when you start identifying your arguments.  Then use ampersand (**&**) from that point on.
```mailto://user@hostname?arg1=key1&arg2=key2```

_In your case, you specified the question mark an additional 2 more times._ 

Most likely the URL couldn't be _fully_ parsed properly as a result.

**Comment by frumpymoons** [comment]
I feel dumb now. This of course fixed my issue.
