### ISSUE TITLE
Make startup notification optional

### ISSUE THREAD

**Issue by stueliueli** [pyouroboros/ouroboros#253]
Thanks for this nice tool.

It would be very nice to have a configuration option, whether or not I want to be informed when ouroboros runs.
At the moment I always get two Mails or IFTTT notifications. One with just the information that ouroboros has started (even when it does not update anything), and then one with the information which containers were upgraded.

If I use Ouroboros via CRON daemon, I'll get the startup notification every time the container runs. That usually contains no real value for me, but it fills my inbox. (At the moment, I'm filtering it via content filter rules in my inbox, but it would be nice if Ouroboros would be configurable to not always send a startup notification, something like `--send-startup-notification=false` with a default to `true` or whatever).

Thank you :)

**Comment by circa10a** [comment]
Merged into develop
#261
