### ISSUE TITLE
Issue when using private repo

### ISSUE THREAD

**Issue by EugeneKallis** [pyouroboros/ouroboros#255]
Set my user and password via environment variables and i see this in the logs

2019-03-07 19:37:42 : CRITICAL : dockerclient : Couldn't pull. Skipping. Error: 404 Client Error: Not Found ("pull access denied for sha256, repository does not exist or may require 'docker login'")

**Comment by circa10a** [comment]
Can you post your ouroboros config by running with the log level set to debug. It'll be the first entry after starting in the log output

**Comment by circa10a** [comment]
@EugeneKallis any updates?

**Comment by EugeneKallis** [comment]
@circa10a Sorry for no response. Im new to using Github and didn't see the notifications. 

`Ouroboros configuration: {'interval': 30, 'docker_sockets': ['unix://var/run/docker.sock'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'repo_user': '<removed>', 'repo_pass': '<removed>', 'cleanup': True, 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'self_update': True, 'hostname': '131059034d04', 'docker_tls_verify': True}`

This issue happens randomly for some reason. Looking at the logs now it happened last night multiple times but then it works.

Another thing that has been happening,  I'm running 2 dockers from the same repo. One uses the latest tag and my other uses a dev tag. For some reason when I check the image in portainer for the dev container it shows 2 images linked to it. So my DEV container will be linked to both latest and dev images and when i ssh into the box it shows code from the latest tag. I hope I'm explaining this right.

**Comment by DirtyCajunRice** [comment]
That would normally happen because a manifest file has linked latest to dev. This is unfortunately a repo maintainer issue and not a ouroboros issue. Because it is intermittent this shows the current code is working and there is either an internet or repo issue on your end. Feel free to re-open if you can consistently reproduce tho!

**Comment by EugeneKallis** [comment]
When you say repo issue, do you mean an issue with Docker hub? All im doing is building and pushing to docker hub.

**Comment by williamhatch** [comment]
hi, I set up a local private docker registry... how to config that to use ouroboros?
