### ISSUE TITLE
Docker TLS verify: Does it  support server and client-side auth, or only server-side auth?

### ISSUE THREAD

**Issue by pyunramura** [pyouroboros/ouroboros#256]
Referencing issue #154 

I noted that the resolution to the issue involved creating ca certificates and client certificates and keys in the /etc/docker/certs.d/$SERVER:$PORT directory which I assume should be mapped to the same inside of the container.

Does this setup currently support server and client-side auth, or only server-side auth? I ask because in attempt to connect to my docker hosts on my internal network I'm met with the error: 
`ERROR : ouroboros : Could not connect to socket tcp://********2.103:2376. Check your config`

The current setup for the ouroboros develop branch is running on host 192.168.2.100 and connecting to tcp://192.168.2.103:2376 with the ca.crt client.cert and client.key files in /etc/docker/certs.d/192.168.2.103:2376/ directory, which is mapped to the same inside the container.

My current configuration for remote commands is working in bash by placing the cert and key files in the ~/.docker directory, as well as setting the docker host as an endpoint in portainer using server and client-side auth.

So far I've tried adjusting the tcp:// options to the hostname of the docker host and regenerating keys for both client and server with no joy.

Any insight into the server and client-side tls auth question would be very appreciated, and plese let me know if you need any more information.

**Comment by circa10a** [comment]
@DirtyCajunRice I just noticed, there's docs for tls verify but not for tls itself. Could you add those?

**Comment by DirtyCajunRice** [comment]
I have added the client documentation here: https://github.com/pyouroboros/ouroboros/wiki/Usage#docker-tls

This implemented client certificates only.
