### ISSUE TITLE
Not ignoring containers specified

### ISSUE THREAD

**Issue by RichardMore** [pyouroboros/ouroboros#258]
I have specified some containers/images in the IGNORE env part, but when ouroboros is run it still tries to pull them and of course it fails and results with an error. Is my config wrong or is this an issue?

docker-compose ouroboros part:
....
  ouroboros:
    image: pyouroboros/ouroboros
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=...
      - SELF_UPDATE=true
      - DATA_EXPORT=influxdb
      - INFLUX_URL=influxdb
      - INFLUX_PORT=8086
      - INFLUX_USERNAME=...
      - INFLUX_PASSWORD=...
      - INFLUX_DATABASE=...
      - IGNORE="lnxmngr_lnxmngr lnxsrvcs_lnxsrvcs"
      - LOG_LEVEL=debug
    depends_on:
      - influxdb
....

In the logs I have:
ouroboros_1  | 2019-03-09 16:15:03 : INFO : ouroboros : Version: 1.3.1-master
ouroboros_1  | 2019-03-09 16:15:03 : DEBUG : ouroboros : Ouroboros configuration: {'interval': 300, 'docker_sockets': ['unix://var/run/docker.sock'], 'ignore': ['lnxmngr_lnxmngr', 'lnxsrvcs_lnxsrvcs'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'influx_url': 'influxdb', 'influx_port': 8086, 'influx_username': '...', 'influx_password': '...', 'influx_database': '...', 'data_export': 'influxdb', 'self_update': True, 'hostname': 'bbce988debd9', 'docker_tls_verify': True}
[...]
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : dockerclient : Checking tag: lnxsrvcs_lnxsrvcs:latest
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : auth : Looking for auth config
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : auth : No auth config in memory - loading from filesystem
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : config : No config file found
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : auth : Looking for auth entry for 'docker.io'
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : auth : No entry found
ouroboros_1  | 2019-03-09 16:15:29 : DEBUG : auth : No auth config found
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=lnxsrvcs_lnxsrvcs HTTP/1.1" 404 112
ouroboros_1  | 2019-03-09 16:15:31 : CRITICAL : dockerclient : Couldn't pull. Skipping. Error: 404 Client Error: Not Found ("pull access denied for lnxsrvcs_lnxsrvcs, repository does not exist or may require 'docker login'")
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/fe69458875f3eac3eff340f257c2f21db86bdaceb696f48f896d590cee288af3/json HTTP/1.1" 200 None
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : dockerclient : Checking tag: lnxmngr_lnxmngr:latest
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : auth : Looking for auth config
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : auth : No auth config in memory - loading from filesystem
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : config : No config file found
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : auth : Looking for auth entry for 'docker.io'
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : auth : No entry found
ouroboros_1  | 2019-03-09 16:15:31 : DEBUG : auth : No auth config found
ouroboros_1  | 2019-03-09 16:15:32 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=lnxmngr_lnxmngr HTTP/1.1" 404 110
ouroboros_1  | 2019-03-09 16:15:32 : CRITICAL : dockerclient : Couldn't pull. Skipping. Error: 404 Client Error: Not Found ("pull access denied for lnxmngr_lnxmngr, repository does not exist or may require 'docker login'")
ouroboros_1  | 2019-03-09 16:15:32 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/48344635a18ed6e1c44fbd6955ca590430a8c0e615681233004783b84ddc57a1/json HTTP/1.1" 200 None
[...]

**Comment by mrubli** [comment]
Have you tried specifying the complete container name as given by `docker ps`? Containers are usually named `<project>_<service>_<n>`, so you may have to specify something like this:

```
IGNORE="lnxmngr_lnxmngr_1 lnxsrvcs_lnxsrvcs_1"
```

Doing the equivalent did the trick on my system and in hindsight I suspect it's what caused me to run into the same problem with Watchtower.

That being said, it would be great if Ouroboros had some built-in support for handling this situation more elegantly, either by applying a bit of name mangling magic (e.g. cutting off the project prefix and instance suffix) or by allowing wildcard/regex patterns. At the very least I'd wish for a hint in the documentation. ;-)

**Comment by RichardMore** [comment]
You are right, should have passed the correct container name not the image name to IGNORE.
Thank you!

And do you (or anyone) know if ouroboros could check the base image if an image is built locally?

**Comment by circa10a** [comment]
Ouroboros will only check for updates remotely via pull and update if the hash differs

**Comment by circa10a** [comment]
One alternative solution to the issue above is to specify the `name:` key in your compose file that way the `_1` doesn't get appended.
