### ISSUE TITLE
Update apprise to v0.7.4

### ISSUE THREAD

**Issue by PeterBizQIT** [pyouroboros/ouroboros#266]
Yesterday I switched from watchtower to ouroboros. I also discovered Apprise created support for Gotify. However when I try to use Gotify in the ouroboros Docker image it throws several errors about not supporting gotify:// and gotifys://.

![image](https://user-images.githubusercontent.com/43367597/54670004-f7b6bc80-4af2-11e9-856d-fac115e27df3.png)

The support in Apprise for Gotify was introduced 7 days ago. According to Docker Hub the ourobos docker image was updated about 9 days ago.

Apprise pull request: https://github.com/caronc/apprise/commit/c8778e9a00edc870d28fbf68b846c7f88319834e

Could you please update the docker image with the latest Apprise version?

**Comment by circa10a** [comment]
@DirtyCajunRice
Thoughts on repushing?

**Comment by circa10a** [comment]
you alive @DirtyCajunRice  ?

**Comment by DirtyCajunRice** [comment]
im alive. just been busy. yeah gotta fix one of the jenkins runners then we can

**Comment by DirtyCajunRice** [comment]
I will update the min version today which will push it into dev

**Comment by DirtyCajunRice** [comment]
Will be fixed in the pull
