### ISSUE TITLE
update from docker.elastic.co got unauthorized: authentication required

### ISSUE THREAD

**Issue by bingochen87** [pyouroboros/ouroboros#267]
ouroboros    | 2019-03-21 22:48:12 : DEBUG : dockerclient : Checking tag: docker.elastic.co/beats/filebeat:6.5.4
ouroboros    | 2019-03-21 22:48:12 : DEBUG : image : Sending supplied auth config
ouroboros    | 2019-03-21 22:48:16 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=6.5.4&fromImage=docker.elastic.co%2Fbeats%2Ffilebeat HTTP/1.1" 500 117
ouroboros    | 2019-03-21 22:48:16 : CRITICAL : dockerclient : Invalid Credentials. Exiting
ouroboros    | 2019-03-21 22:48:16 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-03-21 22:47:55 CDT], next run at: 2019-03-21 22:47:55 CDT)" raised an exception
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
ouroboros    |     response.raise_for_status()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
ouroboros    |     raise HTTPError(http_error_msg, response=self)
ouroboros    | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=6.5.4&fromImage=docker.elastic.co%2Fbeats%2Ffilebeat
ouroboros    | 
ouroboros    | During handling of the above exception, another exception occurred:
ouroboros    | 
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 79, in _pull
ouroboros    |     return_image = self.client.images.pull(tag, auth_config=self.config.auth_json)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 441, in pull
ouroboros    |     repository, tag=tag, stream=True, **kwargs
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 400, in pull
ouroboros    |     self._raise_for_status(response)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
ouroboros    |     raise create_api_error_from_http_exception(e)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
ouroboros    |     raise cls(e, response=response, explanation=explanation)
ouroboros    | docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://docker.elastic.co/v2/beats/filebeat/manifests/6.5.4: unauthorized: authentication required")
ouroboros    | 
ouroboros    | During handling of the above exception, another exception occurred:
ouroboros    | 
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouroboros    |     retval = job.func(*job.args, **job.kwargs)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 296, in update
ouroboros    |     updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 255, in socket_check
ouroboros    |     latest_image = self.pull(current_tag)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 178, in pull
ouroboros    |     return self._pull(tag)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 94, in _pull
ouroboros    |     exit(1)
ouroboros    |   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
ouroboros    |     raise SystemExit(code)
ouroboros    | SystemExit: 1

**Comment by circa10a** [comment]
Are you passing `REPO_USER` and `REPO_PASS`? Could you share your config and scrub sensitive information

**Comment by DirtyCajunRice** [comment]
If no response in 24 hours will close pending
