### ISSUE TITLE
Feature request: Add list of monitored services/containers in startup notification

### ISSUE THREAD

**Issue by NowayIndustries** [pyouroboros/ouroboros#268]
Would it be possible to extend the startup notification to include a list of monitored services/containers, possibly even add a list of the ones *not* being monitored?

I'm having some issues with my swarm stacks not updating their labels properly, and thus getting ouroboros setup the way I want.

Basically I want to have some more concrete information about my setup/config on startup, perhaps something like:
```
Host: ouroboros
Time: 2019-03-23 00:16:57
Interval: 500

Monitored services/containers:
- cloud_app; nextcloud:latest
- cloud_db; postgres:10

Ignored services/containers:
- wiki; solidnerd/bookstack:latest
```

**Comment by DirtyCajunRice** [comment]
Not monitored are not even fed through as saved data to ouro and i dont feel they should. I dont see an issue with showing monitored tho

**Comment by DirtyCajunRice** [comment]
Actually.. it might be tricky as the notification is sent once and this information would be potentially across multiple hosts

**Comment by DirtyCajunRice** [comment]
Yeah this information is established after startup and inside a thread not accessible to the startup notification. It would also make the notifications reeeeally long for some people with 50+ containers per host and multiple hosts causing a denial of notification. We tried but it doesnt seem feasible.
