### ISSUE TITLE
Feature Request: Pre/post update script hooks

### ISSUE THREAD

**Issue by foundObjects** [pyouroboros/ouroboros#269]
It'd be really nice to be able to fire hook scripts pre/post update. This would allow the user to hook into the update process and trigger volume backup for persistent data before bringing up the new container and to fire a validation and/or rollback script post update to handle broken updates.

I'm thinking the pre-update hook should fire after stopping the existing container and before launching the new one, and the post-update script could fire after launching the new container.

**Comment by circa10a** [comment]
We actually already do support post update webhooks.
Please see: https://github.com/pyouroboros/ouroboros/wiki/Notifications

**Comment by DirtyCajunRice** [comment]
So i dont think we would add a totally separate function to the notification platform... but we could absolutely separate out a "pre" and "post" notification call and you could use the json:// to do with what you needed. Would that work for you?

**Comment by DirtyCajunRice** [comment]
Closing from no response

**Comment by foundObjects** [comment]
Apologies, I missed these email notifications a couple of weeks ago (transitioning back to gmail from inbox has been murder for stuff like this.)

Pre and post notifications that I can use as triggers are exactly what I'm looking for -- pre to snapshot persistent volume data pre update and post to fire validation and/or rollback jobs post update. If this ends up going in could you provide a trivial example showing how to fire shell scripts using these, I'm a still little stupid with docker automation.

Cheers, and thanks!

**Comment by Freekers** [comment]
+1 from me for this feature request.

This PR for watchtower does exactly what I want/need, but since it's development is dead, it never got merged/approved: https://github.com/containrrr/watchtower/pull/197

**Comment by clushie** [comment]
I'm evaluating Ouroboros right now and I'd be happy if this feature was there as well.

For example I'd would run a `docker exec postgres pg_dump ...` before running an upgrade of postgres or a web-application connected to the database (which is possible running `./manage.py migrate` after upgrading to the newer docker image).

Do you think Ouroboros should include this functionality or should such a thing be implemented at a different spot?

A workaround I could imagine is running Ouroboros in [dry_run](https://github.com/pyouroboros/ouroboros/wiki/Usage#dry-run), check its output/response (maybe doable as Python module) and then execute within the containers the planned commands before upgrading.

Though I wonder how this all interacts without having something as #288 implemented (rollback on health failure).

Maybe I should investigate into docker swarm instead?
