### ISSUE TITLE
Feature request: version policy

### ISSUE THREAD

**Issue by smlx** [pyouroboros/ouroboros#272]
Thanks for the great software!

In Keel, you can specify the Semantic Versioning policy to follow for an image. The Keel documentation explains the feature well:

* https://keel.sh/v1/guide/documentation.html#Policies

It would be great to have this in ouroboros too.

**Comment by DirtyCajunRice** [comment]
i dont think this would work honestly as tags do not always mean manifest files and manifest is new enough that lots have yet to adopt it. Without manifests theres not reliable way to establish the version as labels arent a forced version requirement. In addition lots of containers do not follow a versioning scheme. Im going to look into it more tho

**Comment by smlx** [comment]
I'm not sure what you mean by manifests.

I was thinking it would work like this, for example with [grafana](https://hub.docker.com/r/grafana/grafana/tags):

* docker container running `grafana/grafana:6.0.2`
* labelled `com.ouroboros.policy=minor`

Ouroboros now upgrades the container using the 6.x.x series of tags, but won't upgrade to 7.x.x (a major release).

**Comment by DirtyCajunRice** [comment]
how exactly do you think it will know when 6.1.0 is released? Ouroboros is querying the current tag and seeing if the SHA has changed. The only way for ouroboros to know if there was another version would be to do a web scrape of that repo to see what past/future tags are available, or to pull the :latest image down every single time, bloating a users system with unwanted images until such a time as the label is satisfied. 

Does this make sense?

**Comment by smlx** [comment]
It could use the HTTP API. But yes, I guess it would require a scrape to check.

e.g. https://hub.docker.com/v2/repositories/grafana/grafana/tags/

**Comment by DirtyCajunRice** [comment]
We use the dockerpy wrapper. Implementing 2 queries would overly bloat the code for something that would only apply to random containers that actually adhere to the semantic versioning scheme. Not to mention the regex required to account for all the nuanced differences of v#.#.#/#.#.#/#.#/#/#.#.#-dev etc etc etc. If this becomes available via the python wrapper it would be much simpler to implement, although still the nuances and regex stated above. I think ill leave this as a group discussion for a while and see others opinions on the desire for it as well as wait for input from @circa10a

**Comment by circa10a** [comment]
I think there's too many variables to do this consistently. Consider tags like 6.1.0-alpine. 6.1.0-stretch. some folks use underscores. 
The better way IMO is to basically subscribe to a version like grafana:6 (if it existed) and you would basically get all the 6.x.x updates. Nginx follows this pattern.
I agree with @DirtyCajunRice that this would really bloat the code for something that wouldn't always work which would result in more and more issues about why someone's tagging pattern doesn't match any predefined patterns in ouroboros.
