### ISSUE TITLE
Pushover notification sent twice

### ISSUE THREAD

**Issue by Olympic80** [pyouroboros/ouroboros#274]
I get double notification from pushover for the same event. I've got two hosts monitored by Ouroboros. Don't know if this related.
Thanks.

**Comment by DirtyCajunRice** [comment]
each host will get notifications. this is by design

**Comment by Olympic80** [comment]
Perhaps, I wasn't clear enough. Notification gets sent for the same host twice. Both notification absiolutely identical: Host/socket, Containers monitored number etc., all are the same in both notifications.

**Comment by DirtyCajunRice** [comment]
pictures, log, config?

**Comment by Olympic80** [comment]
I've figured this out. This happens when there are 2 devices defined in the Pushover parameter:
`- NOTIFIERS="pover://xxxxxxxxxxxxxxxxxxxxxxxx/iPhone/iPad"`
Once second device is removed it works fine, only 1 notification received.
