### ISSUE TITLE
Healthcheck section not re-applied after container update

### ISSUE THREAD

**Issue by Olympic80** [pyouroboros/ouroboros#275]
Healthcheck section not re-applied after container update.

Example of the docker compose file:
`    healthcheck:
      test:           ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval:       1m30s
      timeout:        10s
      retries:        3
      start_period:  40s`

**Comment by circa10a** [comment]
Fixed in develop. Release to follow shortly.
