### ISSUE TITLE
Resend notification on failure

### ISSUE THREAD

**Issue by MardukMason** [pyouroboros/ouroboros#277]
I use gotify to send end recieve notifications and if ouroboros updates the gotify container, the following error appears:

WARNING : NotifyJSON : Failed to send JSON notification (error=502).

This means, the servie is not ready to recieve the webhook. Is it possibly to resend the notification on failure? 
Something like: 
send notification -> error
wait 1 Minute, second try
wait 1 minute, third try.

**Comment by DirtyCajunRice** [comment]
this is a slippery slope as some people have their containers updating as often as every minute. If this was added it could spawn repeated building threads of failures. This isnt a ouroboros issue but a notification service issue. I feel you should address your notification provider to address this.
