### ISSUE TITLE
Updated containers are sometimes not started

### ISSUE THREAD

**Issue by simonszu** [pyouroboros/ouroboros#279]
I have an issue where sometimes updated containers are not started. Unfortunately i do not find anything in the logs, just `2019-04-04 09:53:23 : INFO : dockerclient : dokuwiki will be updated`. However, the dokuwiki container wasn't running after that, i had to start it manually. 

Is this a known issue, or: How can i obtain more logs?

**Comment by circa10a** [comment]
Can you try passing the loglevel flag or environment variable and setting it to debug?
We'll need any errors logged from that

**Comment by DirtyCajunRice** [comment]
Going to close this out from no response. This has been happening with static ips and we have fixed it in develop
