### ISSUE TITLE
Not writing to InfluxDB

### ISSUE THREAD

**Issue by menteb** [pyouroboros/ouroboros#281]
The docker makes a connection to InfluxDB as shown in the logs:

```
DEBUG : connectionpool : http://********0.0.2:60611 "GET /query?q=SHOW+DATABASES&db=********borosdb HTTP/1.1" 200 None
DEBUG : dataexporters : Influxdb database existence check passed for ********borosdb
```

But nothing seems to get written to InfluxDB.

`SELECT count("count") FROM "Ouroboros" GROUP BY "container"` returns nothing.

In my docker-compose.yml I have the following related environment variables:
```
      ...
      - DATA_EXPORT=influxdb
      - INFLUX_URL=10.0.0.2
      - INFLUX_PORT=60611
      - INFLUX_USERNAME=ouroboros
      - INFLUX_PASSWORD=ouroboros
      - INFLUX_DATABASE=ouroborosdb
      ...
```
There are no errors in the log, which is set to DEBUG for this purpose.
Interval is set to 300.

Any ideas?

**Comment by DirtyCajunRice** [comment]
If you are getting database existence passed it is talking. Try doing a simple `select * from Ouroboros`

**Comment by menteb** [comment]
Returns nothing.

**Comment by leonjza** [comment]
I also don't seem to be getting any metrics written to InfluxDB with a similar configuration as @menteb
