### ISSUE TITLE
matrix webhook issue since docker update

### ISSUE THREAD

**Issue by lorenzo95** [pyouroboros/ouroboros#286]
Hello, ouroboros tried to update itself for me last night since the latest tag was updated and it died on all my servers due to the notifiers. 
I was running 1.3.0 with this line without issues for a few weeks:

docker run -d --restart unless-stopped \
  --name ouroboros \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --hostname="${HOSTNAME}" \
  -e TZ=America/Edmonton \
  -e CRON="$(shuf -i 0-59 -n 1) 4 * * *" \
  -e LATEST=true \
  -e CLEANUP=true \
  -e LOG_LEVEL=info \
  -e SELF_UPDATE=true \
  -e NOTIFIERS="matrix://Steve_zklr4t@10.6.77.208:9000/api/v1/matrix/hook/expUW0cq7qu203mgxWRrGevnM2pif7y81ooWPbmJMcnNALU0TucrIVHXCYzklr4t/?webhook=slack&format=markdown" \
  pyouroboros/ouroboros

which translates to user@token/?...    via http
I also tried the above replacing ?webhook with ?mode=slack

all i get now is 
2019-04-09 21:44:35 : WARNING : NotifyMatrix : Failed to send Matrix notification: Page not found., error=404.

if I start the above with pyouroboros/ouroboros:1.3.0 it works fine again. 

Thank you

**Comment by DirtyCajunRice** [comment]
This is because apprise was updated. please refer to their docs
