### ISSUE TITLE
[Feature Request] the only reason I would avoid using this is healthcheck awareness.

### ISSUE THREAD

**Issue by Leopere** [pyouroboros/ouroboros#288]
I would desperately want this technology if it would be aware of the upgrade status of the containers and auto-rollback and notify on failure.

Basically as a user: I would love to have a tool that would attempt to preserve uptime as well as do automatic upgrades.  If the container themselves don't report healthy within a specified amount of time then do a rollback to the previous container image.  If it does report healthy then remove/clean up old images.

I realize this is a fairly complex suggestion but even with docker being docker and the goal of containers being stated as to be as ephemeral as possible (stateless) you don't always achieve the degree of stability you want.

**Comment by Leopere** [comment]
Don't get me wrong I'm currently writing this into several of my docker containers that have no deps or real repercussions for automatic updates.

**Comment by circa10a** [comment]
In your scenario, honestly I don't think ouroboros is the solution, but rather kubernetes.

**Comment by Leopere** [comment]
@circa10a Why go that complex?

**Comment by DirtyCajunRice** [comment]
this is native to swarm.

**Comment by Leopere** [comment]
@DirtyCajunRice oh interesting, have you got a link to this?  I think it would be an excellent feature to have on smaller single hosts with a bunch of potentially brittle microservices.

**Comment by DirtyCajunRice** [comment]
just read up on updating an image to a swarm service.

**Comment by Leopere** [comment]
Do you think that they're basically aiming to have docker swarm stacks replace the functionality of docker-compose?

**Comment by DirtyCajunRice** [comment]
no. they have totally different purposes, but you are trying to do a docker swarm feature in regular docker. So thats my suggestion.

**Comment by Leopere** [comment]
Thanks for the details I will definitely have a look at that feature but unfortunately at the moment upgrading to a swarm from a single node host is a bit out of my scope.  I am aware that you can technically have a single host swarm but all of my docker-compose microservices stacks are focused on docker-compose for portability and publishability purposes.

**Comment by Leopere** [comment]
Also for future people looking at this thread https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/ is what I imagine that @DirtyCajunRice is referring to.
