### ISSUE TITLE
Try to guess precise version tag when updating

### ISSUE THREAD

**Issue by lgnap** [pyouroboros/ouroboros#292]
I set containers to be updated by ouroboros to `latest` or `1` (repo following the semver naming).

This means that `1.0.1` or `1.1.0` release will trigger an update of `1` tags.
Same thing for `latest`, it have often a "more complete" tag behind (gitea): https://hub.docker.com/r/gitea/gitea/tags
`1`, `1.8`, `1.8.0` are probably the same (all are updated 2 days ago at the redaction time).

It's interesting to have `1.8.0` instead of hash behind into the notification

Thanks

**Comment by circa10a** [comment]
To confirm, when you push a new 1.X tag, you're also pushing on top of the existing `1` tag?

**Comment by DirtyCajunRice** [comment]
not only is this not widely done, but is insanely confusing for users. 
1. you should not do what you are doing. lol
2. even if it were common, which it is not, it cannot reliably “decide” that x tag is more important than y tag as there is no standard for what you are doing... because it is wrong
