### ISSUE TITLE
Where is code for grafana dashboard?

### ISSUE THREAD

**Issue by paulfantom** [pyouroboros/ouroboros#309]
It would be nice to host grafana dashboard code (json file) here or in some other repo to allow collaboration in development of that code.

**Comment by DirtyCajunRice** [comment]
the json file is publicly available on the grafana.com website with a big "download json" link right next to it https://grafana.com/dashboards/9728. You can absolutely add whatever you want and make it your own, or suggest a change and post it here. I maintain multiple projects that use grafana and it is not realistic nor worth it to host here and on grafana.com when it does exactly what it is intended to do.

**Comment by paulfantom** [comment]
It is available, but there is no possibility to contribute any changes to it.

**Comment by DirtyCajunRice** [comment]
Its grafana and not a sibling of this project, only a courtesy. As is the premise of grafana. It is there solely as an example to let people see what they _could_ do with the data. You are putting way too much stock into an example only dash.
