### ISSUE TITLE
Prometheus metrics issues 

### ISSUE THREAD

**Issue by nickgreen239** [pyouroboros/ouroboros#312]
I am having a couple issues related to metrics. I am using Prometheus as my monitoring database and Grafana to view the data. I noticed gaps in the data so I started to troubleshoot and I found that the Prometheus scrapes to Ouroboros are very slow compared to other scrapes. It takes 5-10s to scrape Ouroboros when other targets only take 10ms or less. I used nmap from another computer on the network and port 8000 shows as open most of the time but it randomly switches to filtered occasionally. The other ports for containers on this same host do not exhibit this issue, They consistently show open from nmap.

My other issue may simply be the way Ouroboros works currently. I noticed after resetting or recreating the container (my apologies for not being able to remember which one I did) that the metrics for container updates was also reset. Is there a way to have Ouroboros keep track of that data even after a reset/recreate. Especially in the case of Ouroboros needing to be updated. Could that be a feature request if there is currently not a way to do that? Possibly attaching a persistent volume to store the data in?

**Comment by DirtyCajunRice** [comment]
This was worked though in discord. Prometheus isnt designed to be long lived metrics, but you can achieve this with influxdb! :D
