### ISSUE TITLE
Notification of update only

### ISSUE THREAD

**Issue by mbologna** [pyouroboros/ouroboros#341]
Is there a way to use pyouroboros to notify when a container image is updated (e.g. redis:latest)?

Of course, I am running a container using that image - I just want a notification when the image is updated and can be pulled from a public registry.

**Comment by circa10a** [comment]
@mbologna Maybe you're looking for [dry-run](https://github.com/pyouroboros/ouroboros/wiki/Usage#dry-run) ?

**Comment by mbologna** [comment]
Yes, this might work with the notification option enabled. Thanks!
