### ISSUE TITLE
Discord notifications not working with ouroboros

### ISSUE THREAD

**Issue by mattgphoto** [pyouroboros/ouroboros#351]
Related to https://github.com/caronc/apprise/issues/179 which has been fixed in apprise... can the fix for this be merged into ouroboros?

**Comment by FatCyclone** [comment]
You can update pip manually in the container (or build your own) while waiting for an image update.

**Comment by quorn23** [comment]
> You can update apprise manually in the container (or build your own) while waiting for an image update.

for reference
`docker exec -it ouroboros_updatingcontainers /bin/sh
pip install apprise --upgrade`

**Comment by mattgphoto** [comment]
> > You can update apprise manually in the container (or build your own) while waiting for an image update.
> 
> for reference
> `docker exec -it ouroboros_updatingcontainers /bin/sh`
> `pip install apprise --upgrade`

Thank you! I had to separate out the commands, but I think this worked! We'll see tomorrow at 4am!

**Comment by DirtyCajunRice** [comment]
The update has been merged to develop and will be built saturday. Im at re:invent and cant till then. Thanks yall.

**Comment by quorn23** [comment]
Thanks for the note @DirtyCajunRice 
Would you consider pushing the dev branch to the docker hub in the future?

**Comment by DirtyCajunRice** [comment]
@quorn23 it is on dockerhub. Just couldnt be built.
