### ISSUE TITLE
Update fail after Ouroboros update

### ISSUE THREAD

**Issue by pavellzubkov** [pyouroboros/ouroboros#357]
Thank you for great project! But i get some trouble...
After last auto update (v. 1.4.3) all my images updating stopped. After starting  - error:

`ERROR : dockerclient : Issue detecting my_image's image tag.`

to solve problem i've delete ouroboros image and download it again by start my docker-compose file.
After that all ok.

I plan to make copy of your's image to avoid that behaviour after some unexpected update.

**Comment by DirtyCajunRice** [comment]
all that was updated was apprise. Nothing to do with anything related
