### ISSUE TITLE
about metrics

### ISSUE THREAD

**Issue by nesys** [pyouroboros/ouroboros#366]
Hi folks,

I've installed ouroboros and prometheus in two containers.

I've understood at least 3 metrics should see about containers:

'containers_updated',
'containers_being_monitored'
'all_containers_updated'

But in prometheus I see only 'containers_being_monitored'. Maybe because I've updated all my containers before installing prometheus, and I need to wait next update to see something?

Please advise
thanks

Andrea

**Comment by circa10a** [comment]
@nesys you are correct. Those metrics will be created when an update has occurred.
