### ISSUE TITLE
[Question] Cache and data stored in previous containers data folder

### ISSUE THREAD

**Issue by epicylon** [pyouroboros/ouroboros#373]
Hey, quick question (and pardon my GitHub-etiquette) 

If I use a container like Jellyfin/Emby/Plex, will the stored data in my old container's data folder (like subtitles, user-input media description etc.) be overwritten by the new updated container?

Thanks!

**Comment by circa10a** [comment]
@epicylon as long as the data is stored in a docker volume or host mounted volume, yes.
