### ISSUE TITLE
few questions about ouroboros + influxdb

### ISSUE THREAD

**Issue by nesys** [pyouroboros/ouroboros#374]
Hi folks,

I've configured ouroboros in a docker container, and it works like a charm. Now I'm migrating from prometheus to influxdb, and I have two questions:

- what is the SELECT command to see the monitored_containers? I'm using this for the updated, and it works: SELECT count("count") FROM "Ouroboros" GROUP BY "container"

- About the updated containers, I see the time is totally wrong (1970-01-01 at 1 AM). What should be the issue here? and how to solve?

thanks for your support
Andrea

**Comment by nesys** [comment]
first question easy :)

SELECT "monitored_containers" FROM "Ouroboros" GROUP BY "container"

**Comment by nesys** [comment]
My TZ is Europe/Rome

**Comment by circa10a** [comment]
@nesys you set the timezone in the container via environment variable right?

**Comment by nesys** [comment]
yep correct

**Comment by circa10a** [comment]
if you run `date` on the host, what do you get?

**Comment by nesys** [comment]
host means on my Synology NAS? Sun Mar  1 19:19:04 CET 2020

**Comment by circa10a** [comment]
hmmmm
can you try mounting in `/etc/localtime` like so:

```
 -v /etc/localtime:/etc/localtime:ro
```

**Comment by nesys** [comment]
let me try.
In the meantime I've tried to call "date" in docker terminal in ouroboros container. Same time as the host.

Mmmm ...

**Comment by nesys** [comment]
It seems it solved the issue, thanks @circa10a 

I'm trying to see the container updated with this query:

SELECT "updated_count" FROM "ouroboros"."autogen"."Ouroboros" GROUP BY "container"

But I see only time and number of updates ... but not seeing the container_name ...

Any suggestion?

**Comment by nesys** [comment]
It seems this is the right way to follow:

SELECT "count" FROM "ouroboros"."autogen"."Ouroboros" GROUP BY "container"
