### ISSUE TITLE
Update Stopped containers

### ISSUE THREAD

**Issue by Devo-McDuff** [pyouroboros/ouroboros#380]
Hi.

Looking through the documentation, I don't think this is possible but I'm just double checking in-case I've misunderstood. Anyway, is it possible to have stopped containers updated also?

Thanks.

**Comment by bd8392** [comment]
I would also need this, because I'm running cron-job containers from crazy-max/swarm-cronjob...they only run once every configured period

**Comment by DirtyCajunRice** [comment]
No.
