### ISSUE TITLE
Support multi-architecture Docker images

### ISSUE THREAD

**Issue by dannysauer** [pyouroboros/ouroboros#78]
It's a poor user experience needing to know which tag maps to their architecture.  Docker supports figuring that out with magic!

https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6

**Comment by circa10a** [comment]
just have to play with modifying the docker daemon on travis to enable experimental features :wink:

**Comment by DirtyCajunRice** [comment]
@dannysauer so you know, DOCKER may know with manifest files... but ci building of arm was... an experience. We should have it pushed to master soon but holy moly that was a much deeper hole than initially expected

**Comment by dannysauer** [comment]
I'll be super interested in seeing that process's outcome, as I'm starting to build a mixed x86, Pi zero, and Pi3b+ kubernetes cluster today. ;)

**Comment by DirtyCajunRice** [comment]
fixed :)
