### ISSUE TITLE
Ignore not working as expected

### ISSUE THREAD

**Issue by nicx** [pyouroboros/ouroboros#98]
Hi, I try to use the "ignore" option by ENV on my Synology Docker, but its not working as expected:

IGNORE=homegear throws this log message:

`2019-01-14 13:41:25 : INFO : dockerclient : Ignoring container(s): h, o, m, e, g, e, a, r`

Is this a bug or is it a formatting problem by myself?

**Comment by circa10a** [comment]
@nicx Thanks for reporting the issue. We'll take a deeper look.
For now to by pass, can you try using the [command line argument](https://github.com/pyouroboros/ouroboros/wiki/Usage#monitor-select-containers)

**Comment by circa10a** [comment]
@DirtyCajunRice shouldn't `monitor` and `ignore` go here?: https://github.com/pyouroboros/ouroboros/blob/master/pyouroboros/config.py#L101

**Comment by nicx** [comment]
hm... just tried it anyway: seems the option is working, only the logfile output is malformatted ;)

**Comment by circa10a** [comment]
@nicx Can you share a snippet of the output?

**Comment by nicx** [comment]
@circa10a what do you need exactly? I only have the log output mentioned above. When deleting the ENV for ignore it immediately started updating this container and I get this message:


```
2019-01-14 13:54:39 : INFO : dockerclient : homegear will be updated | stdout
-- | --
```

 that is why I think the IGNORE is working.

**Comment by circa10a** [comment]
@nicx If possible, all the output from 1 pass of ouroboros

**Comment by DirtyCajunRice** [comment]
yeah. another split slipped through lol

**Comment by DirtyCajunRice** [comment]
This bug is fixed in develop :)
